### ISSUE TITLE
Add new (MWDI) responseCodes to list of internally defined responseCodes

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#1030]
Add new responseCodes required by MWDI to the [list of internally defined responseCodes](
https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/HowToDefineErrorMessages/HowToDefineErrorMessages.md).

Additional explanations about the new error codes 461, 471 and 533 can be found in the related issue [MWDI#977](https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/997).

```
    '461':
      description: 'Response in case the (parent) topology object provided in the request (body or path) is not found in the cache.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 461
                maximum: 461
                format: int32
              message:
                type: string
                enum:
                  - 'Not available. The topology (parent) object is currently not found in the cache.'
    '471':
      description: 'Response in case the (child) topology object specified in the request (body or path) does not exist within the cache.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 471
                maximum: 471
                format: int32
              message:
                type: string
                enum:
                  - '(Child) topology object not existing. Cache informs about addressed resource unknown.'
    '533':
      description: 'Response in case the referenced resource for an connected device does not exist at the controller.'
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                minimum: 533
                maximum: 533
                format: int32
              message:
                type: string
                enum:
                  - 'Resource unknown. The resource for the connected device does not exist at the Controller.'
 ```
