### ISSUE TITLE
UUID as a Regex in ProfileList

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#173]
**Analyse first** cost and benefit of expressing the known parts of the UUID as a Regex.

```
  - profile-name: ActionProfile
    uuid: *-action-p-10??
    operation-name: string
    label: string
    request: string
    input-value-list:
      - field-name: string
        unit: string
    display-in-new-browser-window: boolean
```
potentially to be changed into somewhat like:
```
  - profile-name: ActionProfile
    uuid: string
      pattern: [regex for "*-action-p-10??"]
    operation-name: string
    label: string
    request: string
    input-value-list:
      - field-name: string
        unit: string
    display-in-new-browser-window: boolean
```
