### ISSUE TITLE
Client for addressing databases required

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#235]
In general, information that is required for connecting to the database, which is holding the application data, shall be documented in the CONFIGfile and be made available for configuration on the REST interface.

In a first step, connecting to ElasticSearch shall be made available.

It turned out that several specific attributes are required for connecting to ElasticSearch.
A specific ElasticSearchClient class shall be defined as a client to the HttpClient class.

**Comment by openBackhaul** [comment]
Artifact to be temporarily stored:
```
                                  - description: 'elastic search client'
                                    type: object
                                    required:
                                      - local-id
                                      - layer-protocol-name
                                      - elastic-search-client-interface-1-0:elastic-search-client-interface-pac
                                    properties:
                                      local-id:
                                        type: string
                                      layer-protocol-name:
                                        type: string
                                        enum:
                                          - 'operation-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_OPERATION_LAYER'
                                          - 'http-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_HTTP_LAYER'
                                          - 'tcp-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_TCP_LAYER'
                                          - 'elastic-search-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_ELASTIC_SEARCH_LAYER'
                                          - 'operation-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_OPERATION_LAYER'
                                          - 'http-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_HTTP_LAYER'
                                          - 'tcp-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_TCP_LAYER'
                                      elastic-search-client-interface-1-0:elastic-search-client-interface-pac:
                                        type: object
                                        required:
                                          - elastic-search-client-interface-configuration
                                          - elastic-search-client-interface-status
                                        properties:
                                          elastic-search-client-interface-configuration:
                                            type: object
                                            required:
                                              - elastic-search-user
                                              - elastic-search-password
                                              - index-alias
                                            properties:
                                              elastic-search-user:
                                                type: string
                                              elastic-search-password:
                                                type: string
                                              index-alias:
                                                type: string
                                              service_records_policy:
                                                type: string
# hier die Parameter einsetzen, die in ElasticRepository.js hard codiert sind
                                              



                                              detailed-logging-is-on:
                                                type: boolean
                                          elastic-search-client-interface-status:
                                            type: object
                                            required:
                                              - operational-state
                                              - life-cycle-state
                                            properties:
                                              elastic-searchal-state:
                                                type: string
                                                enum:
                                                  - 'elastic-search-client-interface-1-0:OPERATIONAL_STATE_TYPE_AVAILABLE'
                                                  - 'elastic-search-client-interface-1-0:OPERATIONAL_STATE_TYPE_UNAVAILABLE'
                                                  - 'elastic-search-client-interface-1-0:OPERATIONAL_STATE_TYPE_NOT_YET_DEFINED'
                                              life-cycle-state:
                                                type: string
                                                enum:
                                                  - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_EXPERIMENTAL'
                                                  - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OPERATIONAL'
                                                  - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_DEPRECATED'
                                                  - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OBSOLETE'
                                                  - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_UNKNOWN'
                                                  - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_NOT_YET_DEFINED'
```

**Comment by openBackhaul** [comment]
**Proposed ElasticSearchClient:**

```
- description: 'elastic search client'
  type: object
  required:
    - local-id
    - layer-protocol-name
    - elastic-search-client-interface-1-0:elastic-search-client-interface-pac
  properties:
    local-id:
      type: string
    layer-protocol-name:
      type: string
      enum:
        - 'operation-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_OPERATION_LAYER'
        - 'http-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_HTTP_LAYER'
        - 'tcp-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_TCP_LAYER'
        - 'operation-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_OPERATION_LAYER'
        - 'elastic-search-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_ELASTIC_SEARCH_LAYER'
        - 'http-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_HTTP_LAYER'
        - 'tcp-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_TCP_LAYER'
    elastic-search-client-interface-1-0:elastic-search-client-interface-pac:
      type: object
      required:
        - elastic-search-client-interface-configuration
        - elastic-search-client-interface-status
      properties:
        elastic-search-client-interface-configuration:
          type: object
          required:
            - auth
            - index-alias
            - service-records-policy
          properties:
            auth:
              type: object
              minProperties: 1
              additionalProperties: false
              properties:
                api-key:
                  type: string
                  description: 'base64EncodedKey'
            index-alias:
              type: string
            service-records-policy:
              type: string
        elastic-search-client-interface-status:
          type: object
          required:
            - operational-state
            - life-cycle-state
          properties:
            elastic-searchal-state:
              type: string
              enum:
                - 'elastic-search-client-interface-1-0:OPERATIONAL_STATE_TYPE_AVAILABLE'
                - 'elastic-search-client-interface-1-0:OPERATIONAL_STATE_TYPE_UNAVAILABLE'
                - 'elastic-search-client-interface-1-0:OPERATIONAL_STATE_TYPE_NOT_YET_DEFINED'
            life-cycle-state:
              type: string
              enum:
                - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_EXPERIMENTAL'
                - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OPERATIONAL'
                - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_DEPRECATED'
                - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OBSOLETE'
                - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_UNKNOWN'
                - 'elastic-search-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_NOT_YET_DEFINED'

```

**Comment by MartinSunal** [comment]
few nits:
- _elasticsearch_ is one word (not elastic-search)
- _elastic-searchal-state_ is typo and it should be _operational-state_

I am not sure if CONFIGfile should contain state like _elastic-search-client-interface-status_

In case everything is configurable via REST during runtime, what are the expectations to happen when:
- index-alias is changed
- service-record-policy is changed

**Comment by openBackhaul** [comment]
**The attached proposal for the ElasticSearchClient consolidates the following changes:**
- Policy::phases::hot::min_age, Policy::phases::hot::actions::rollover::max_age and Policy::delete::min_age have been added to the proposed ElasticSearchClient.
- service-record-policy has been made fully available for configuration in the proposed ElasticSearchClient.
- elastic-searchal-state has been replaced by operational-state
- elastic-search has been replaced by elasticsearch 

**Further clarification:**
- Would like the OaM section of the REST API to represent operational and life-cycle state of the connection to the ElasticSearch, too. Would like the REST API and the content of the CONFIGfile to stay in synch.
- If index-alias is changed, it is expected that the application is reading/writing data stored under the new index-alias in the database (no matter, whether index-alias has been used before, or not).
- If service-record-policy is changed, it is expected that:  
  - In case of existing name, attributes of existing service-record-policy shall be changed and applied.  
  - In case of new name, new service-record-policy shall be created and applied.  
 
**Updated Proposed ElasticSearchClient:**
(Please, feel invited to comment.)
```
- description: 'elasticsearch client'
  type: object
  required:
    - local-id
    - layer-protocol-name
    - elasticsearch-client-interface-1-0:elasticsearch-client-interface-pac
  properties:
    local-id:
      type: string
    layer-protocol-name:
      type: string
      enum:
        - 'operation-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_OPERATION_LAYER'
        - 'http-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_HTTP_LAYER'
        - 'tcp-server-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_TCP_LAYER'
        - 'operation-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_OPERATION_LAYER'
        - 'elasticsearch-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_ELASTIC_SEARCH_LAYER'
        - 'http-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_HTTP_LAYER'
        - 'tcp-client-interface-1-0:LAYER_PROTOCOL_NAME_TYPE_TCP_LAYER'
    elasticsearch-client-interface-1-0:elasticsearch-client-interface-pac:
      type: object
      required:
        - elasticsearch-client-interface-configuration
        - elasticsearch-client-interface-status
      properties:
        elasticsearch-client-interface-configuration:
          type: object
          required:
            - auth
            - index-alias
            - service-records-policy
          properties:
            auth:
              type: object
              minProperties: 1
              additionalProperties: false
              properties:
                api-key:
                  type: string
                  description: 'base64EncodedKey'
            index-alias:
              type: string
            service-records-policy:
              type: object
              required:
                - service-records-policy-name
                - phases
              properties:
                service-records-policy-name:
                  type: string
                master-timeout:
                  type: string
                timeout:
                  type: string
                description:
                  type: string
                project:
                  type: object
                  properties:
                    name:
                      type: string
                    department:
                      type: string
                phases:
                  type: object
                  properties:
                    hot:
                      type: object
                      properties:
                        min-age:
                          type: string
                        actions:
                          type: object
                          properties:
                            forcemerge:
                              type: object
                              required:
                                - max-num-segments
                              properties:
                                max-num-segments:
                                  type: integer
                                index-codec:
                                  type: string
                            readonly:
                              type: object
                            rollover:
                              type: object
                              minProperties: 1
                              additionalProperties: false
                              properties:
                                max-age:
                                  type: string
                                max-docs:
                                  type: integer
                                max-size:
                                  type: string
                                max-primary-shard-size:
                                  type: string
                                max-primary-shard-docs:
                                  type: integer
                                min-age:
                                  type: string
                                min-docs:
                                  type: integer
                                min-size:
                                  type: string
                                min-primary-shard-size:
                                  type: string
                                min-primary-shard-docs:
                                  type: integer
                            searchable-snapshot:
                              type: object
                              required:
                                - snapshot-repository
                              properties:
                                snapshot-repository:
                                  type: string
                                force-merge-index:
                                  type: boolean
                            set-priority:
                              type: object
                              required:
                                - priority
                              properties:
                                priority:
                                  type: integer
                            shrink:
                              type: object
                              properties:
                                number-of-shards:
                                  type: integer
                                max-primary-shard-size:
                                  type: string
                            unfollow:
                              type: object
                    warm:
                      type: object
                      properties:
                        min-age:
                          type: string
                        actions:
                          type: object
                          properties:
                            allocate:
                              type: object
                              minProperties: 1
                              additionalProperties: false
                              properties:
                                number-of-replicas:
                                  type: integer
                                total-shards-per-node:
                                  type: integer
                                include:
                                  type: object
                                  properties:
                                    box-type:
                                      type: string
                                      enum:
                                        - 'hot'
                                        - 'warm'
                                        - 'cold'
                                        - 'frozen'
                                        - 'delete'
                                exclude:
                                  type: object
                                  properties:
                                    box-type:
                                      type: string
                                      enum:
                                        - 'hot'
                                        - 'warm'
                                        - 'cold'
                                        - 'frozen'
                                        - 'delete'
                                require:
                                  type: object
                                  properties:
                                    box-type:
                                      type: string
                                      enum:
                                        - 'hot'
                                        - 'warm'
                                        - 'cold'
                                        - 'frozen'
                                        - 'delete'
                                    storage:
                                      type: string
                                      enum:
                                        - 'high'
                            forcemerge:
                              type: object
                              required:
                                - max-num-segments
                              properties:
                                max-num-segments:
                                  type: integer
                                index-codec:
                                  type: string
                            migrate:
                              type: object
                              properties:
                                enabled:
                                  type: boolean
                            readonly:
                              type: object
                            set-priority:
                              type: object
                              required:
                                - priority
                              properties:
                                priority:
                                  type: integer
                            shrink:
                              type: object
                              properties:
                                number-of-shards:
                                  type: integer
                                max-primary-shard-size:
                                  type: string
                            unfollow:
                              type: object
                    cold:
                      type: object
                      properties:
                        min-age:
                          type: string
                        actions:
                          type: object
                          properties:
                            allocate:
                              type: object
                              minProperties: 1
                              additionalProperties: false
                              properties:
                                number-of-replicas:
                                  type: integer
                                total-shards-per-node:
                                  type: integer
                                include:
                                  type: object
                                  properties:
                                    box-type:
                                      type: string
                                      enum:
                                        - 'hot'
                                        - 'warm'
                                        - 'cold'
                                        - 'frozen'
                                        - 'delete'
                                exclude:
                                  type: object
                                  properties:
                                    box-type:
                                      type: string
                                      enum:
                                        - 'hot'
                                        - 'warm'
                                        - 'cold'
                                        - 'frozen'
                                        - 'delete'
                                require:
                                  type: object
                                  properties:
                                    box-type:
                                      type: string
                                      enum:
                                        - 'hot'
                                        - 'warm'
                                        - 'cold'
                                        - 'frozen'
                                        - 'delete'
                                    storage:
                                      type: string
                                      enum:
                                        - 'high'
                            migrate:
                              type: object
                              properties:
                                enabled:
                                  type: boolean
                            readonly:
                              type: object
                            searchable-snapshot:
                              type: object
                              required:
                                - snapshot-repository
                              properties:
                                snapshot-repository:
                                  type: string
                                force-merge-index:
                                  type: boolean
                            set-priority:
                              type: object
                              required:
                                - priority
                              properties:
                                priority:
                                  type: integer
                            unfollow:
                              type: object
                    frozen:
                      type: object
                      properties:
                        min-age:
                          type: string
                        actions:
                          type: object
                          properties:
                            searchable-snapshot:
                              type: object
                              required:
                                - snapshot-repository
                              properties:
                                snapshot-repository:
                                  type: string
                                force-merge-index:
                                  type: boolean
                            unfollow:
                              type: object
                    delete:
                      type: object
                      properties:
                        min-age:
                          type: string
                        actions:
                          type: object
                          required:
                            - delete
                          properties:
                            delete:
                              type: object
                              properties:
                                delete-searchable-snapshot:
                                  type: boolean
                            wait-for-snapshot:
                              type: object
                              required:
                                - policy
                              properties:
                                policy:
                                  type: string
        elasticsearch-client-interface-status:
          type: object
          required:
            - operational-state
            - life-cycle-state
          properties:
            operational-state:
              type: string
              enum:
                - 'elasticsearch-client-interface-1-0:OPERATIONAL_STATE_TYPE_AVAILABLE'
                - 'elasticsearch-client-interface-1-0:OPERATIONAL_STATE_TYPE_UNAVAILABLE'
                - 'elasticsearch-client-interface-1-0:OPERATIONAL_STATE_TYPE_NOT_YET_DEFINED'
            life-cycle-state:
              type: string
              enum:
                - 'elasticsearch-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_EXPERIMENTAL'
                - 'elasticsearch-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OPERATIONAL'
                - 'elasticsearch-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_DEPRECATED'
                - 'elasticsearch-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_OBSOLETE'
                - 'elasticsearch-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_UNKNOWN'
                - 'elasticsearch-client-interface-1-0:LIFE_CYCLE_STATE_TYPE_NOT_YET_DEFINED'
```
