### ISSUE TITLE
FileProfile for addressing application data files required

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationPattern#287]
Issue #105 for Splitting up the LOADfile is requesting for:
>
> - If application data is stored in one or several files, name and location of these files shall also be seen as part of the configuration, which is to be stored in the CONFIGfile.
>

- Adding the following entry into the [ProfileList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/ApplicationPattern+profiles.yaml):
```
  - profile-name: 'FileProfile'
    uuid: '^[a-z]{2,6}-([0-9]+)-([0-9]+)-([0-9]+)-file-p-[0-9]{3}$'
    capability:
      file-identifier: string
      file-description: string
    configuration:
      file-path: string
      user-name: string
      password: string
      operation: string
```

- Adding the following entry into the [ProfileInstanceList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/ApplicationPattern+profileInstances.yaml):
```
  - profile-name: 'FileProfile'
    uuid: '*-file-p-???' ## TODO: Replace "*" by ApplicationID and ReleaseNumber and ??? by SequenceNumber
    capability:
      file-identifier: ## TODO: Add invariant identifier of the referenced file
      file-description: ## TODO: Add a description of the content of the referenced file
    configuration:
      file-path: ## TODO: Add file name, like e.g. '../application-data/application-data.json'
      user-name: ## TODO: If file protected, add user-name
      password: ## TODO: If file protected, add password
      operation: ## TODO: Choose from read/write/off

  ## TODO: Potentially add further instances of FileProfile
```

- OAS
  - Adding the following entry into the OAM Layer - Individual Part: /core-model-1-4:control-construct: -> control-construct/profile-collection/profile/  anyOf:
  ```
	- description: 'file profile'
	  type: object
	  required:
		- uuid
		- profile-name
		- file-profile-1-0:file-profile-pac
	  properties:
		uuid:
		  type: string
		profile-name:
		  type: string
		  enum:
			- 'action-profile-1-0:PROFILE_NAME_TYPE_ACTION_PROFILE'
			- 'file-profile-1-0:PROFILE_NAME_TYPE_FILE_PROFILE'
			- 'integer-profile-1-0:PROFILE_NAME_TYPE_INTEGER_PROFILE'
			- 'string-profile-1-0:PROFILE_NAME_TYPE_STRING_PROFILE'
		file-profile-1-0:file-profile-pac:
		  type: object
		  required:
			- file-profile-capability
			- file-profile-configuration
		  properties:
			file-profile-capability:
			  type: object
			  required:
				- file-identifier
				- file-description
			  properties:
				file-identifier:
				  type: string
				file-description:
				  type: string
			file-profile-configuration:
			  type: object
			  required:
				- file-path
			  properties:
				file-path:
				  type: string
				user-name:
				  type: string
				password:
				  type: string
				operation:
				  type: string
				  enum:
					- 'file-profile-1-0:OPERATION_TYPE_READ_ONLY'
					- 'file-profile-1-0:OPERATION_TYPE_READ_WRITE'
					- 'file-profile-1-0:OPERATION_TYPE_OFF'
					- 'file-profile-1-0:OPERATION_TYPE_NOT_YET_DEFINED'
  ```

  - Adding the following entry into the OAM Layer - Individual Part: /core-model-1-4:control-construct/profile-collection/profile={uuid}: -> core-model-1-4:profile oneOf:
  ```
	  - description: 'file profile'
		type: object
		required:
		  - core-model-1-4:uuid
		  - core-model-1-4:profile-name
		  - file-profile-1-0:file-profile-1-0:file-profile-pac
		properties:
		  core-model-1-4:uuid:
			type: string
		  core-model-1-4:profile-name:
			type: string
			enum:
		  	  - 'action-profile-1-0:PROFILE_NAME_TYPE_ACTION_PROFILE'
			  - 'file-profile-1-0:PROFILE_NAME_TYPE_FILE_PROFILE'
			  - 'integer-profile-1-0:PROFILE_NAME_TYPE_INTEGER_PROFILE'
			  - 'string-profile-1-0:PROFILE_NAME_TYPE_STRING_PROFILE'
		  file-profile-1-0:file-profile-pac:
			type: object
			required:
			  - file-profile-capability
			  - file-profile-configuration
			properties:
			  file-profile-capability:
				type: object
				required:
				  - file-identifier
				  - file-description
				properties:
				  file-identifier:
					type: string
				  file-description:
					type: string
			  file-profile-configuration:
				type: object
				required:
				  - file-path
				properties:
				  file-path:
					type: string
				  user-name:
					type: string
				  password:
					type: string
				  operation:
					type: string
					enum:
					  - 'file-profile-1-0:OPERATION_TYPE_READ_ONLY'
					  - 'file-profile-1-0:OPERATION_TYPE_READ_WRITE'
					  - 'file-profile-1-0:OPERATION_TYPE_OFF'
					  - 'file-profile-1-0:OPERATION_TYPE_NOT_YET_DEFINED'
  ```

  - Adding the following paths to the OAM Layer - Individual Part:
    -   /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-capability/file-identifier:
    - /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-capability/file-description:
    - /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/file-path:
    - /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/user-name:
    - /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/password:
    - /core-model-1-4:control-construct/profile-collection/profile={uuid}/file-profile-1-0:file-profile-pac/file-profile-configuration/operation:
 
- No change to the CONFIGfile, because applying a APPDATAfile is individual to the application.
