### ISSUE TITLE
Update serviceList template with TAC-apps v2-0-0

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#311]
The template contains entries vor Tiny Application Controller applications with version 1-0-0.  
The version numbers should be changed to 2-0-0/2.0.0.

Changes are to be done for the http clients:
- the release numbers, ip-address and tcp port need to be modified for 2-0-0/2.0.0 apps according to [FakeIp Addresses](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/IpAddresses/IpAddresses.md) 
- also the uuids in the http clients having the TAC applications as targets need to be modified.

E.g.:
```
 - http-client:
      application-name: RegistryOffice
      release-number: 1.0.0   -> change to 2.0.0
      uuid: xx-1-0-0-http-c-bm-ro-1-0-0-000    -> change to xx-1-0-0-http-c-bm-ro-2-0-0-000
    tcp-client:
      ip-address: 1.1.3.1   -> change to 1.1.3.8
      tcp-port: 3001   -> change to 3008
      uuid: xx-1-0-0-tcp-c-bm-ro-1-0-0-000   -> change to xx-1-0-0-tcp-c-bm-ro-2-0-0-000
    operation-clients:
      own-oam:
        basic:
          - service-name: /v1/register-application
            uuid: xx-1-0-0-op-c-bm-ro-1-0-0-000   -> change to xx-1-0-0-op-c-bm-ro-2-0-0-000
...
```
