### ISSUE TITLE
Update OAS template with TAC-apps v2-0-0

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/ApplicationPattern#314]
The template contains entries for Tiny Application Controller applications with version 1-0-0.
The entries related to the version number should be changed to 2-0-0/2.0.0.

E.g. in URLs where the target is one of the TAC applications there's still the 1-0-0 contained.
Example: the URL contains -ro-1-0-0-, it should be changed to -ro-2-0-0-

*# individual callbacks to be added here  
PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement:  
https://[/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-ro-1-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/domain-name or /core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-**ro-1-0-0**-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-address/ip-address/ipv-4-address]:[/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-tcp-c-bm-**ro-1-0-0**-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-port][/core-model-1-4:control-construct/logical-termination-point=*-1-0-0-op-c-bm-**ro-1-0-0**-001/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]:*

It needs to be verified if the version numbers also must be changed in examples, e.g.:
```
    parameters:
      - in: path
        name: uuid
        required: true
        schema:
          type: string
          pattern: '^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-tcp-c-([bi][ms])-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-000$'
          example: 'ro-1-0-0-tcp-c-bm-or-1-0-0-000'
```
*example* could also be changed to ro-2-0-0.
