### ISSUE TITLE
requesting clarification : behaviour of local-address attribute for formulating callbacks

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationPattern#459]
•	In /v1/register-yourself service (image 1 below), as per the local-address attribute description of http-address and https-address, it is allowed only for updating either ip-address or domain-name and not both. Also, this attribute will be written into the config file but will not be directly used for further communication.
•	But, as per tcp-server-interface-configuration/local-address definition (in image 2 below) of OAM layer, we can understand that, unlike http-client/remote-address, both attributes can be present in config file at same time. 
•	On the other hand, as per the below decision made (in below mail chain) “If a domain-name is added via a service(for example for v1/redirect-service-request-information) , then the server-side code will include the attributes required for including domain-name along with the values and delete the ip-address attribute at the same time.” This clarification has been made for a service trying to access “http-client/remote-protocol” 

Kindly requesting you to clarify which will be given priority if both ipv-4-address and domain-name are present in case of http-server/local-address. 
I remember one of our conversations where you stated that if both attributes are present “ipv-4-address” will be prioritized and will be chosen for further operations.

Doubt scenario:
But I got a doubt in one scenario. If the /v1/register-yourself request-body contains attribute domain-name for http-address/local-address in it, this may be an indication that the domain-name is available for the application, and this could be used for further communication. This also may indicate that ipv-4-address is expired or less preferred to domain-name. 
Problem:
But, as per our specification, domain-name will be written into the config file but will not be directly used for communication and the server should choose the attribute from config file. If ipv-4-address will be prioritized and will be taken for further communication, there will be possibility for failures of further callback requests which uses this chosen ipv-4-address. 

Please let me know if my understanding is not correct. If my understanding is correct, I would like to provide below proposals. 

Proposal 1:
The incoming address attribute “either domain-name or ipv-4-address” can be allowed to be directly used for formulating callbacks after writing into config file.
Proposal 2:
               As per the decision made in below mail chain “If a domain-name is added via a service(for example for v1/redirect-service-request-information) , then the server-side code will include the attributes required for including domain-name along with the values and delete the ip-address attribute at the same time.”. 
We can apply the same rule to http-server/local-address, but an application knowing both its own ipv-4-address and domain-name (if available) will be more informative. Also, as per image 2, both attributes are allowed in config file. 

Kindly let us know your views. Thank you.
![http-address of register-yourself](https://user-images.githubusercontent.com/88484011/207546539-e3dbfe3b-4c67-4581-9f1d-d6fe44e49e43.png)
![local-address_PUT request schema_OAM layer](https://user-images.githubusercontent.com/88484011/207546548-df054d8a-b026-41f9-bebb-25d58757db30.png)

**Comment by openBackhaul** [comment]
> ...  an application knowing both its own ipv-4-address and domain-name (if available) will be more informative.

More data does not necessarily mean more informative (e.g., if the information are redundant or contradicting).
According to my first feeling the error lays in the CONFIG file potentially holding both domain name and ip address.

Would you agree that 
```
              properties:
                tcp-server-interface-1-0:local-address:
                  type: object
                  minProperties: 1
                  maxProperties: 1
                  additionalProperties: false
                  properties:
                    ipv-4-address:
                      type: string
                      pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                      example: '1.1.4.1'
                    domain-name:
                      type: string
                      pattern: '^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$'
                      example: 'application-pattern.mw-domain.transport.ger.telefonica.com'
```
(see maxProperties statement) would solve the problem?

Would you see any disadvantages from not allowing TcpServer holding both domain name and ip address in the CONFIGfile?
