### ISSUE TITLE
ApplicationPattern.yaml specification does not match Elasticsearch properties 1:1

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/ApplicationPattern#471]
The ApplicationPattern.yaml file specifies Elasticsearch service policy phases properties with "-", whereas Elasticsearch uses "_". This prevents the transition from ES object to valid response to be seamless.

Example: 

**ES output of policy**

```
"policy" : {
      "phases" : {
        "hot" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_size" : "10mb",
              "max_age" : "1d"
            }
          }
        },
        "delete" : {
          "min_age" : "30d",
          "actions" : {
            "delete" : {
              "delete_searchable_snapshot" : true
            }
          }
        }
      }
```

**ApplicationPattern.yaml**

```
rollover:
      type: object
      minProperties: 1
      additionalProperties: false
      properties:
         max-age:
            type: string
         max-docs:
            type: integer
         max-size:
            type: string
         max-primary-shard-size:
            type: string
         max-primary-shard-docs:
            type: integer
         min-age:
            type: string
         min-docs:
             type: integer
         min-size:
            type: string
         min-primary-shard-size:
             type: string
         min-primary-shard-docs:
             type: integer
```

Suggestions:
- either remove phases details from service record policy definition
or 
- adjust the individual parameters to exactly match Elasticsearch
