### ISSUE TITLE
putTcpServerLocalAddress example requires a change

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationPattern#517]
As per the schema definition for the OAM service putTcpServerLocalAddress , maximum allowed entry is 1. But, in the example , both ipv-4-address and domain-name are present.

```
{
  "tcp-server-interface-1-0:local-address": {
    "ipv-4-address": "1.1.4.1",
    "domain-name": "application-pattern.mw-domain.transport.ger.telefonica.com"
  }
}
```
Proposal : 
Either we can keep only "ipv-4-address" or  "domain-name".

Impact : 
No impact in server side. 
In the swagger GUI , an example responseBody with both "ipv-4-address" and  "domain-name" will be present.

**Comment by openBackhaul** [comment]
Change for an example on schema level like:
```
            schema:
              type: object
              required:
                - tcp-server-interface-1-0:local-address
              properties:
                tcp-server-interface-1-0:local-address:
                  type: object
                  minProperties: 1
                  maxProperties: 1
                  additionalProperties: false
                  properties:
                    ipv-4-address:
                      type: string
                      pattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
                    domain-name:
                      type: string
                      pattern: '^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$'
            example:
              tcp-server-interface-1-0:local-address:
                ipv-4-address: '1.1.4.1'
```
