### ISSUE TITLE
OnfAttributes for TCPServer do not match config file

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationPattern#634]
```
const TCP_SERVER = {
    CAPABILITY: "tcp-server-interface-capability",
    CONFIGURATION: "tcp-server-interface-configuration",
    IPV_4_ADDRESS: "ipv-4-address",
    IP_ADDRESS: "ip-address",
    DOMAIN_NAME: "domain-name",
    LOCAL_PORT: "local-port"
};
```

specification file:

```
tcp-server-interface-1-0:tcp-server-interface-pac:
  type: object
  required:
  - tcp-server-interface-configuration
  properties:
  tcp-server-interface-configuration:
    type: object
    required:
      - description
      - local-protocol
      - local-address
      - local-port
    properties:
      description:
        type: string
      local-protocol:
        type: string
      local-address:
        type: object
        minProperties: 1
        maxProperties: 1
        additionalProperties: false
        properties:
          ipv-4-address:
            type: string
          domain-name:
            type: string
      local-port:
        type: integer
```

Server-side code needs unification.
