### ISSUE TITLE
Specification of TCPServer interface configuration does not match TCPClient interface configuration

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationPattern#638]
TCP client local-address has different element structure as TCP server remote-address which results in different objects ( there is additional 'ip-address' element in TCP client)

TCP Client:

```
tcp-client-interface-1-0:tcp-client-interface-pac:
type: object
required:
  - tcp-client-interface-configuration
properties:
  tcp-client-interface-configuration:
    type: object
    required:
      - remote-protocol
      - remote-address
      - remote-port
    properties:
      remote-protocol:
        type: string
      remote-address:
        type: object
        minProperties: 1
        maxProperties: 1
        additionalProperties: false
        properties:
          ip-address:
            type: object
            minProperties: 1
            additionalProperties: false
            properties:
              ipv-4-address:
                type: string
          domain-name:
            type: string
      remote-port:
        type: integer
```

Data:
```
"tcp-client-interface-configuration": {
  "remote-protocol": "tcp-client-interface-1-0:PROTOCOL_TYPE_HTTP",
  "remote-address": {
    "ip-address": {
      "ipv-4-address": " >>> IpAddress and Port (below) of the existing release <<< "
    }
  },
  "remote-port": 1000
}
```

TCP Server:
```
tcp-server-interface-1-0:tcp-server-interface-pac:
  type: object
  required:
  - tcp-server-interface-configuration
  properties:
  tcp-server-interface-configuration:
    type: object
    required:
      - description
      - local-protocol
      - local-address
      - local-port
    properties:
      description:
        type: string
      local-protocol:
        type: string
      local-address:
        type: object
        properties:
          ipv-4-address:
            type: string
          domain-name:
            type: string
      local-port:
        type: integer
```

Data:
```
"tcp-server-interface-configuration": {
    "description": "Without TLS layer",
    "local-protocol": "tcp-server-interface-1-0:PROTOCOL_TYPE_HTTP",
    "local-address": {
      "ipv-4-address": " >>> ownIpAddress and Port (below) <<< "
    },
    "local-port": 3008
  }
```
